name: Build & Publish Docker Image

on:
  push:
    branches:
      - develop



jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit }}


      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use

          IFS=',' read -r -a tags <<< "latest"
          tag_args=""
          for tag in "${tags[@]}"; do
            tag_args="$tag_args -t ${{ secrets.DOCKERHUB_USER }}/pgbackweb:$tag"
          done

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            $tag_args \
            -f ./docker/Dockerfile \
            --push .

      
